### ISSUE TITLE
typescript support ++

### ISSUE THREAD

**Issue by achmadk** [OsmiCSX/osmicsx#10]
Permisi, Mas @DeVoresyah . Ini saya lagi coba oprek-oprek library-nya. Mau coba bikin versi typescript-nya. cuma masih stuck di fungsi `connect`-nya, biar bisa dipake sama developer yang pake typescript.

Mungkin untuk pengembangan selanjutnya, selain adanya dukungan typescript (minimal ada file berekstensi `.d.ts` yang terdefinisi di file package.json), bisa menambahkan provider menggunakan React Context API sama hooks.

**Comment by DeVoresyah** [comment]
halo mas, untuk typescript sebenarnya kami pun ingin mendukung hal itu. Namun saat ini kami belum menemukan orang yang bisa membantu kami untuk mengembangkan versi typescript nya

**Comment by andriyfm** [comment]
Bakal keren sih kalo support typescript, ayo om @achmadk bantuin. Btw sya baru mau coba nih OsmiCSX nya om @DeVoresyah

**Comment by DeVoresyah** [comment]
> Bakal keren sih kalo support typescript, ayo om @achmadk bantuin. Btw sya baru mau coba nih OsmiCSX nya om @DeVoresyah

berhubung saya bukan developer typescript jadi belum bisa bantu nih hehe, untuk next update major di OsmiCSX saya mau buat metode styling nya lebih beda lagi, contoh:
```
<View class="flex bg-blue-500 items-center justify-center">
  <Text class="text-center text-white text-lg">Hello World!</Text>
</View>
```

**Comment by andriyfm** [comment]
> > Bakal keren sih kalo support typescript, ayo om @achmadk bantuin. Btw sya baru mau coba nih OsmiCSX nya om @DeVoresyah
> 
> berhubung saya bukan developer typescript jadi belum bisa bantu nih hehe, untuk next update major di OsmiCSX saya mau buat metode styling nya lebih beda lagi, contoh:
> 
> ```
> <View class="flex bg-blue-500 items-center justify-center">
>   <Text class="text-center text-white text-lg">Hello World!</Text>
> </View>
> ```

Lebih readable sih yang ini. smangat om

**Comment by pcprinz** [comment]
Hey Guys,

I'd suggest you to rewrite everything in typescript and go with v4.1 though the new [Template Literal Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types) probably fit perfectly into your project. This might save you a huge amount of boilerplate.

And please try to write in english if you want to reach public collaborators.

**Comment by DeVoresyah** [comment]
> Hey Guys,
> 
> I'd suggest you to rewrite everything in typescript and go with v4.1 though the new [Template Literal Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types) probably fit perfectly into your project. This might save you a huge amount of boilerplate.
> 
> And please try to write in english if you want to reach public collaborators.

Hi, thanks for your suggestion. It's really helpful and I really appreciate it, I don't have any base knowledge in typescript so I think I can't help so much to rewrite it in typescript.

Currently, I'm working on OsmiCSX 0.6.0 which will bring a huge major update and a new method of styling in React Native
