### ISSUE TITLE
resizeMode for image styling and Width Height in string percentage

### ISSUE THREAD

**Issue by shirokun20** [OsmiCSX/osmicsx#21]
Excuse me, you can add resizeMode for image props when using styles and then add Width and Height in the form of percent strings like the example below:
`<Image source={Images.appLogo} style={{ width: "100%", height: "40%", resizeMode: "contain", }} />`

Thank you

**Comment by DeVoresyah** [comment]
hi, can you please write it in English? thanks

**Comment by shirokun20** [comment]
Oke sir

**Comment by deyusf** [comment]
`resizeMode` already in pre-defined style, I think @DeVoresyah forget to add it into documentation

**Comment by DeVoresyah** [comment]
> `resizeMode` already in pre-defined style, I think @DeVoresyah forget to add it into documentation

haha sorry, yeah I missed it. Will update soon
