### ISSUE TITLE
Cannot read property getColorScheme of undefined

### ISSUE THREAD

**Issue by muhammad-ihsan** [OsmiCSX/osmicsx#23]
Hello, i trying to use this package for my react native project with detail below:

```
"react": "16.9.0",
"react-native": "0.61.4",
"osmicsx": "^0.6.10",
```

But when i apply a style like:
```
render() {
	return(
        <View>
            <Text style={apply('text-black')}>Hello World!</Text>
        </View>
	)
}

```
its return error
`
TypeError: Cannot read property 'getColorScheme' of undefined
`

**Comment by DeVoresyah** [comment]
Hello,
I think react native `0.61.x` doesn't support dark mode yet. I recommend you to use OsmiCSX `0.5.1`
