### ISSUE TITLE
add option for maxWidth and maxHeight

### ISSUE THREAD

**Issue by rizbud** [OsmiCSX/osmicsx#25]
in react native StyleSheet there are ```maxWidth: number``` and ```maxHeight: number```.
before update we can define it in ```CustomTheme.js``` like this
```
"max-w-200": { maxWidth: 200 },
"max-h-200": { maxHeight: 200 }
```
after update, there is no documentation to add maxWidth and maxHeight

**Comment by DeVoresyah** [comment]
also add minWidth & minHeight

Example:
```
apply("min-w-100 min-h-100")
```
