### ISSUE TITLE
Having control like Width and Height

### ISSUE THREAD

**Issue by abdoerrahiem** [OsmiCSX/osmicsx#26]
Can't control value for these: Top, Left, Right, Bottom, Z-Index, Padding, Margin, Font Size, Letter Spacing, Line Height, Border Width, Border Radius like Width and Height did.

My intention is if I want to make top/left/right/bottom higher than 10 or -10, I can just use:
`apply("top-50")`
`apply("-top-50")`

Or if I want to make margin 20, I can just use:
`apply("m-20")`
In the docs, I have to use this to make same result and have to add manually for non-existing value (like margin 22):
`apply("m-5")`

**Comment by DeVoresyah** [comment]
will be available in the next update~! 🎉
