### ISSUE TITLE
width & height custom config scale

### ISSUE THREAD

**Issue by branislaav** [OsmiCSX/osmicsx#32]
Would be great to have config also for width and height similar like tailwindcss has. 
Also, it would be great if width and height could support percentage values. e.q. `w-1/2 `

**Comment by DeVoresyah** [comment]
> Would be great to have config also for width and height similar like tailwindcss has.
> Also, it would be great if width and height could support percentage values. e.q. `w-1/2 `

for width & height percentage, it's already available `w/{percentage-amount}`

example:
`w/50` the output is 50% width based on window screen

but for percentage width string like `{ width: '50%' }` that not based on window screen, we will update in next release
