### ISSUE TITLE
Missing + Enhancements

### ISSUE THREAD

**Issue by toras123** [OsmiCSX/osmicsx#49]
I was not able to  find a way to provide a height: 100% relative to the parent just like the "full" - for width 100% without using flex.

Also with Spacing, there is no way to provide responsive margins/paddings, so I am using react-native-sizes-matters, but can not really integrate it with padding and margins since they are custom and can not be any value, for eg: `pl-${scale(14)}`, I know I can provide this in the custom theme file, but again for each value this will make it longer and harder, So I think a good solution for this is to give an option to provide a pl-{anyValue} and same for margins

**Comment by DeVoresyah** [comment]
in the next release, you can achieve a width & height 100% that relative to the parents using `w%100` and `h%100`.

but for the responsive padding & margin, you need to define it manually in a custom theme. For example:
```jsx
import { scaleWidth } from 'osmicsx'

export default = {
  spacing: {
    4: scaleWidth(2).width
  }
}
```

you can use it for margin and padding. Example usage:
```jsx
pl-4
ml-4
```
and many more

**Comment by toras123** [comment]
Thank you for support, looking forward for the new release!

**Comment by toras123** [comment]
Another thing that I found out missing or not shown in documentation, is the tint-color of images, not sure how can we write it? eg: tintColor:'white'

**Comment by DeVoresyah** [comment]
> Another thing that I found out missing or not shown in documentation, is the tint-color of images, not sure how can we write it? eg: tintColor:'white'

I didn't realize about the tintColor, will add it asap. Thanks for the feedback

**Comment by DeVoresyah** [comment]
hi @deyusf , can you help me to add this?

**Comment by deyusf** [comment]
> hi @deyusf , can you help me to add this?

okey, doing it right now

**Comment by toras123** [comment]
Thank you for adding it, can you please let me know when and how can I use it with alpha version?

**Comment by DeVoresyah** [comment]
> Thank you for adding it, can you please let me know when and how can I use it with alpha version?

sure, usually we update the version of the next docs.
https://osmicsx.dev/docs/next/intro

**Comment by toras123** [comment]
Thank you, this issue can be closed for now.
