### ISSUE TITLE
Responsive UI clarification 

### ISSUE THREAD

**Issue by KJ-GM** [OsmiCSX/osmicsx#50]
So I just want to clear things out in terms of responsive usage, because I have been facing some issues with responsiveness lately and I was thinking what I am doing wrong, 

**Text Fonts:** I have seen that you have added a list of responsive fonts with certain values corresponding to the usual ones, how can I add a specific font value in the custom theme that is responsive ?

**Images:** I am not really sure how to make images responsive, if you can please show small example?

**Paddings/Margins:** I have seen that you have added the **scaleWidth** and  **scaleHeight** functions. 

Are the scaleWidth and scaleHeight used for responsive spacing only or can they be used in other cases which I am not aware of, if yes where?

Also, if I am missing other tools or facilities that can help for responsiveness, please let us know.

Thank you

**Comment by DeVoresyah** [comment]
hi @toras123 , do you have discord? I want to discuss more before releasing v0.7.0

**Comment by toras123** [comment]
> hi @toras123 , do you have discord? I want to discuss more before releasing v0.7.0

Yes I do, here is my discord: Toras#2778

**Comment by DeVoresyah** [comment]
> > hi @toras123 , do you have discord? I want to discuss more before releasing v0.7.0
> 
> Yes I do, here is my discord: Toras#2778

Friend request sent, from Han Ji-Pyeong
