### ISSUE TITLE
[BUG] Dark theme NOT working with drawer navigation!

### ISSUE THREAD

**Issue by KJ-GM** [OsmiCSX/osmicsx#51]
Theming is not working as expected, 

I have two screens:

First one changes where I use the state(rerenders because of the local state):

this state that cause the rerender =>  **const [theme, setTheme] = useState(appearanceHook.activeTheme)**

Second one dose not change at all(dose not rerender):

Nothing is there except the styling with apply for two texts

I tried to look for the problem in the library , I can see that you would rerender components that use apply using the onPatch by box state tree, but still it is not working here...

I was able to fix this only by adding the observer for my second component which then acts as expected and changes colors accordingly 

This may be caused by the fact that the drawer navigator is used here, but that is still a problem, cause it is not working with drawer so its not compatible

Here is small video that show the problem,

https://user-images.githubusercontent.com/52489083/148435739-623352a0-c048-4479-a914-507a2dc2e16e.mp4

**Comment by rullyokadoc** [comment]
fixed in v1

**Comment by DeVoresyah** [comment]
fixed in v1
