### ISSUE TITLE
Incorrect transform when the condition is not fulfilled on dynamic style

### ISSUE THREAD

**Issue by Diananaa** [OsmiCSX/osmicsx#64]
## Description
i'm using osmicsx 1.1.1, and i want to make dynamic styling based on some conditions. for example : 
``` 
apply("bg-blue-500", disabled && "opacity-50") 
```
so, when the  `disabled` value is `true` . the output is correct : 
```
[{ backgroundColor: "blue" }, { opacity: 0.5 }]
```
but, when the `disabled` is `false`. the  output is correct : 
```
[{ backgroundColor: "blue" }, false]
```

## How to Reproduce
1. Use `apply` method 
2. Write dynamic style with some condition is required
3. Set condition `false`

**Comment by DeVoresyah** [comment]
hi,
thanks for your contribution, I've merge your PR
