### ISSUE TITLE
Typescript error on dynamic style when the the condition is undefined

### ISSUE THREAD

**Issue by Drexyz** [OsmiCSX/osmicsx#67]
### Issue and Steps to Reproduce
There's a condition where the variable that used for the condition is undefined. Example:
```
apply(disabled && "opacity-50")
```
the `disabled` is optional and can be undefined. Then on the vscode showing typescript error like in the screenshot

### Versions
- OsmiCSX v1.1.2
- Expo v47

### Screenshots
![Screen Shot 2023-02-27 at 10 42 35](https://user-images.githubusercontent.com/69439233/221800003-b99651b4-cb30-4689-9315-d423a57acf5f.png)

#### Expected
- Should not showing any typing error

#### Actual
- Showing typescript error on vscode

**Comment by DeVoresyah** [comment]
@Diananaa do you wanna work on this? if not I will handle this
